### ISSUE TITLE
Block verification/building is broken

### ISSUE THREAD

**Issue by pcfreak30** [lightclients/patronum#22]
After the latest hardfork, `headerDataFromWeb3Response` seems to build a wrong header structure.

All uses of `header.hash()` get compared wrongly as a result. All other security checks still seem to run fine though.

This is a somewhat high priority to fix given the nature. I have, in the mean time, disabled block hash verification.

**Comment by shresthagrawal** [comment]
@pcfreak30, thanks for reporting. We will fix this asap.
